# Generated by Django 5.2.7 on 2025-10-15 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NetworkLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Название', max_length=255, verbose_name='Название')),
                ('email', models.EmailField(blank=True, help_text='email', max_length=254, null=True, verbose_name='Email')),
                ('country', models.CharField(blank=True, help_text='Введите назание страны', max_length=100, null=True, verbose_name='Страна')),
                ('city', models.CharField(blank=True, help_text='Введите назание города', max_length=100, null=True, verbose_name='Город')),
                ('street', models.CharField(blank=True, help_text='Введите назание улицы', max_length=100, null=True, verbose_name='Улица')),
                ('house_number', models.PositiveIntegerField(blank=True, help_text='Введите номер дома', max_length=10, null=True, verbose_name='Номер дома')),
                ('level', models.CharField(choices=[('Завод', 'Завод'), ('Розничная сеть', 'Розничная сеть'), ('Индивидуальный предприниматель', 'Индивидуальный предприниматель')], help_text='Уровень доступа', max_length=50, verbose_name='Уровень доступа')),
                ('debt_to_supplier', models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Долг перед поставщиком', max_digits=10, null=True, verbose_name='Долг перед поставщиком')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Звено сети',
                'verbose_name_plural': 'Звено сети',
                'ordering': ['city'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Название продукта', max_length=255, verbose_name='Название продукта')),
                ('model', models.CharField(blank=True, help_text='Модель', max_length=100, null=True, verbose_name='Модель')),
                ('release_date', models.DateField(blank=True, help_text='дата выхода продукта на рынок', null=True, verbose_name='дата выхода продукта на рынок')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
            },
        ),
    ]
