# Generated by Django 5.2.7 on 2025-10-15 20:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('electronics_retail_chain', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='networklink',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='Создавший пользователь', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Создавший пользователь'),
        ),
        migrations.AddField(
            model_name='networklink',
            name='supplier',
            field=models.ForeignKey(blank=True, help_text='Поставщик', null=True, on_delete=django.db.models.deletion.SET_NULL, to='electronics_retail_chain.networklink', verbose_name='Поставщик'),
        ),
        migrations.AddField(
            model_name='product',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='Создавший пользователь', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Создавший пользователь'),
        ),
    ]
