# Generated by Django 5.2.7 on 2025-10-15 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electronics_retail_chain', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='networklink',
            name='products',
            field=models.ManyToManyField(blank=True, null=True, to='electronics_retail_chain.product'),
        ),
        migrations.AlterField(
            model_name='networklink',
            name='house_number',
            field=models.PositiveIntegerField(blank=True, help_text='Введите номер дома', null=True, verbose_name='Номер дома'),
        ),
    ]
